apiVersion: apps/v1 
kind: Deployment
metadata:
  name: test
  namespace: test-test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1 
  template:
    metadata:
      labels:
        app: test
        chaos: "on"
    spec:
      containers:
      - name: test
        image: test:v1
        imagePullPolicy: IfNotPresent
      nodeSelector:
        chaos: "on"
